#prometheus.yml - file
#this must be in the same directory as of docker-compose.yml file

scrape_configs:
- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
    - targets: ['10.30.1.21:8082']
- job_name: 'docker-21'
  static_configs:
    - targets: ['10.30.1.21:9323']
